apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # It is strongly recommended to change this password
  POSTGRES_PASSWORD: "postgres"
  # The DATABASE_URL that other services will use to connect
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/feedback_db"
